// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'mention_light.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MentionLight _$MentionLightFromJson(Map<String, dynamic> json) => MentionLight(
  id: (json['id'] as num).toInt(),
  updateTimeStamp: (json['updateTime'] as num).toInt(),
  dataType: (json['dataType'] as num).toInt(),
  puid: (json['puid'] as num).toInt(),
  type: (json['type'] as num).toInt(),
  operateId: (json['operateId'] as num).toInt(),
  pid: (json['pid'] as num).toInt(),
  number: (json['number'] as num).toInt(),
  recommendNum: (json['recommendNum'] as num?)?.toInt(),
  lightNum: (json['lightNum'] as num).toInt(),
  historyNum: (json['historyNum'] as num).toInt(),
  url: json['url'] as String,
  status: (json['status'] as num).toInt(),
  lastTimeStamp: (json['lastTime'] as num).toInt(),
  threadTitle: json['title'] as String,
  optUid: (json['optUid'] as num).toInt(),
  isVideoNum: (json['isVideo'] as num).toInt(),
  optHeader: json['optHeader'] as String?,
  optUsername: json['optUsername'] as String?,
  optSpaceUrl: json['optSpaceUrl'] as String?,
  titlePrefix: json['titlePrefix'] as String,
  certIconUrl: json['certIconUrl'] as String?,
  certTitle: json['certTitle'] as String?,
  post: LightPost.fromJson(json['post'] as Map<String, dynamic>),
  operators: (json['operators'] as List<dynamic>)
      .map((e) => Operator.fromJson(e as Map<String, dynamic>))
      .toList(),
  createTimeString: json['formatTime'] as String,
);

Map<String, dynamic> _$MentionLightToJson(MentionLight instance) =>
    <String, dynamic>{
      'id': instance.id,
      'updateTime': instance.updateTimeStamp,
      'dataType': instance.dataType,
      'puid': instance.puid,
      'type': instance.type,
      'operateId': instance.operateId,
      'pid': instance.pid,
      'number': instance.number,
      'recommendNum': instance.recommendNum,
      'lightNum': instance.lightNum,
      'historyNum': instance.historyNum,
      'url': instance.url,
      'status': instance.status,
      'lastTime': instance.lastTimeStamp,
      'title': instance.threadTitle,
      'optUid': instance.optUid,
      'isVideo': instance.isVideoNum,
      'optHeader': instance.optHeader,
      'optUsername': instance.optUsername,
      'optSpaceUrl': instance.optSpaceUrl,
      'titlePrefix': instance.titlePrefix,
      'certIconUrl': instance.certIconUrl,
      'certTitle': instance.certTitle,
      'post': instance.post,
      'operators': instance.operators,
      'formatTime': instance.createTimeString,
    };

LightPost _$LightPostFromJson(Map<String, dynamic> json) => LightPost(
  pid: (json['pid'] as num).toInt(),
  tid: (json['tid'] as num).toInt(),
  aid: (json['aid'] as num?)?.toInt(),
  puid: (json['puid'] as num).toInt(),
  username: json['username'] as String,
  userIp: json['userIp'] as String,
  via: (json['via'] as num).toInt(),
  content: json['content'] as String,
  quote: (json['quote'] as num).toInt(),
  createTimeStamp: (json['createTime'] as num).toInt(),
  updateInfo: json['updateInfo'] as String,
  rawPHPAttr: json['attr'] as String,
  score: (json['score'] as num).toInt(),
  preCount: (json['preCount'] as num).toInt(),
  avatarUrlStr: json['header'] as String,
  page: (json['page'] as num).toInt(),
  url: json['url'] as String?,
  lightCount: (json['lightCount'] as num).toInt(),
  quoteLightCount: (json['quoteLightCount'] as num?)?.toInt(),
  isHideInt: (json['isHide'] as num).toInt(),
  quoteIsHide: (json['quoteIsHide'] as num?)?.toInt(),
  auditStatus: (json['auditStatus'] as num).toInt(),
  quoteAuditStatus: (json['quoteAuditStatus'] as num?)?.toInt(),
  isDeleteInt: (json['isDelete'] as num).toInt(),
  quoteIsDeleted: (json['quoteIsDeleted'] as num?)?.toInt(),
  quoteDeleted: (json['quoteDeleted'] as num?)?.toInt(),
  userBannedInt: (json['userBanned'] as num).toInt(),
  quoteInfo: json['quoteInfo'] as String?,
  quotePuid: (json['quotePuid'] as num?)?.toInt(),
  quoteFloor: (json['quoteFloor'] as num?)?.toInt(),
  quoteUsername: json['quoteUsername'] as String?,
  quoteContent: json['quoteContent'] as String?,
  isMerged: json['isMerged'] as String?,
  mergeId: json['mergeId'] as String?,
  mergeTitle: json['mergeTitle'] as String?,
);

Map<String, dynamic> _$LightPostToJson(LightPost instance) => <String, dynamic>{
  'pid': instance.pid,
  'tid': instance.tid,
  'aid': instance.aid,
  'puid': instance.puid,
  'username': instance.username,
  'userIp': instance.userIp,
  'via': instance.via,
  'content': instance.content,
  'quote': instance.quote,
  'createTime': instance.createTimeStamp,
  'updateInfo': instance.updateInfo,
  'attr': instance.rawPHPAttr,
  'score': instance.score,
  'preCount': instance.preCount,
  'header': instance.avatarUrlStr,
  'page': instance.page,
  'url': instance.url,
  'lightCount': instance.lightCount,
  'quoteLightCount': instance.quoteLightCount,
  'isHide': instance.isHideInt,
  'quoteIsHide': instance.quoteIsHide,
  'auditStatus': instance.auditStatus,
  'quoteAuditStatus': instance.quoteAuditStatus,
  'isDelete': instance.isDeleteInt,
  'quoteIsDeleted': instance.quoteIsDeleted,
  'quoteDeleted': instance.quoteDeleted,
  'userBanned': instance.userBannedInt,
  'quoteInfo': instance.quoteInfo,
  'quotePuid': instance.quotePuid,
  'quoteFloor': instance.quoteFloor,
  'quoteUsername': instance.quoteUsername,
  'quoteContent': instance.quoteContent,
  'isMerged': instance.isMerged,
  'mergeId': instance.mergeId,
  'mergeTitle': instance.mergeTitle,
};

Operator _$OperatorFromJson(Map<String, dynamic> json) => Operator(
  uid: (json['uid'] as num?)?.toInt(),
  username: json['username'] as String,
  spaceUrlStr: json['spaceUrl'] as String,
  avatarUrlStr: json['optHeader'] as String,
  certIconUrl: json['certIconUrl'] as String?,
  certTitle: json['certTitle'] as String?,
);

Map<String, dynamic> _$OperatorToJson(Operator instance) => <String, dynamic>{
  'uid': instance.uid,
  'username': instance.username,
  'spaceUrl': instance.spaceUrlStr,
  'optHeader': instance.avatarUrlStr,
  'certIconUrl': instance.certIconUrl,
  'certTitle': instance.certTitle,
};
